# Generated by Django 2.1.1 on 2018-12-24 21:11

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_owner_first_name', models.CharField(default='', max_length=50)),
                ('home_owner_mid_name', models.CharField(default='', max_length=50)),
                ('home_owner_last_name', models.CharField(default='', max_length=50)),
                ('home_owner_phone', models.CharField(default='', max_length=9)),
                ('fire_date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('location_image_url', models.TextField(default='')),
                ('is_admin', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='home',
        ),
    ]
